### ISSUE TITLE
[BUG] Issues encountered regenerating AzureCommuncationChat

### ISSUE THREAD

**Issue by tjprescott** [Azure/autorest.swift#258]
The following were issues encountered regenerating AzureCommunicationChat (https://github.com/Azure/azure-sdk-for-ios/pull/563) that necessitated manual changes:

- [ ] API version was not correctly generated. It used `api-version`, which is an invalid Swift property name.
- [ ] Special client params apiVersion and endpoint were imported from the Swagger but should not be.
- [ ] Endpoint needed to be generated as `$endpoint` to construct the URL. 
- [ ] startTimeString was generated as an invalid symbol. Had to be replaced with `String(describing: startTime, format: Date.Format.iso8601)`
- [ ] `endpoint` was added to the pathParams but should not be. It is part of the base client options.
- [ ] Instantiating a PagedCollection inside of a `FooService` using `self` fails because `FooService` is not a `FooClient`. Have to change from `self` to `self.client`.
- [ ] Old models needed to be manually removed after the code was generated.
- [ ] New files needed to be manually added to the project.
- [ ] Both update methods were generated using `MergePatchObject` but did not correct apply the body parameters. In fact, in these cases, `MergePatchObject` is not needed.

**Comment by sacheu** [comment]
@tjprescott , for 

- [ ] Endpoint needed to be generated as $endpoint to construct the URL. 

- [ ] endpoint was added to the pathParams but should not be. It is part of the base client options.

the change was because we now support Parameterized Host (i.e. custom-baseurl.json in test swagger json. We discussed this earlier and decided $host is just a case of Parameterized host

**Comment by sacheu** [comment]
- [ ] Old models needed to be manually removed after the code was generated.

- [ ] New files needed to be manually added to the project.

@tjprescott , we can't remove the destination directory before the code generation process. Otherwise, AutorestSwift can't compile (in the Package.swift's dependency, it has test/integration/generated directories) due to the fact that the test target needs those generated code.

**Comment by tjprescott** [comment]
Anything we don't think we can address right now, we can separate them out. We don't need to remove the directory, but we should clean the files that might be there in case regeneration renders those files obsolete.
