### ISSUE TITLE
Could not find a branch named ‘CircularReferences’ in https://github.com/tjprescott/Yams.git

### ISSUE THREAD

**Issue by neojf** [Azure/autorest.swift#331]
```
.package(url: "https://github.com/tjprescott/Yams.git", .branch("CircularReferences")),
.package(url: "https://github.com/stencilproject/Stencil.git", .branch("trim_whitespace")),
```

Both CircularReferences branch of Yams and trim_whitespace branch of stencil were removed. Which branch can we use for autorest.swift?

**Comment by tjprescott** [comment]
Try 
`ResolveInternalCircularRefs`

**Comment by neojf** [comment]
Thanks @tjprescott.This branch named trim_whitespace for https://github.com/stencilproject/Stencil was also deleted. Do we have an alternative branch of stencil?

**Comment by neojf** [comment]
Hi @tjprescott , I used ResolveInternalCircularRefs branch for Yams and master branch for Stencil, but I got an error when I generated the swift code:'

<img width="1669" alt="image" src="https://github.com/Azure/autorest.swift/assets/106125231/10f3ca08-e08d-4148-987e-d3bcb9be3127">

I found an error when compling the StencilUtil.swift
<img width="1621" alt="image" src="https://github.com/Azure/autorest.swift/assets/106125231/7ac1dafc-6958-4177-947c-f29289d2b5b8">

**Comment by tjprescott** [comment]
@neojf what are you trying to use Autorest.Swift for?

**Comment by neojf** [comment]
@tjprescott I want to use it to generate swift code based on swagger.json file using this command: `autorest --input-file=swaggerConfig.json --output-folder=./gen/ --namespace=myclient --use=./autorest.swift/`. Is it a correct way to use autorest.swift?

**Comment by tjprescott** [comment]
autorest.swift is an internal tool that is currently only used by the Azure Communication Services Chat team. Today it is in maintenance-only mode. If you are on a Microsoft Service team, I'd recommend you reach out to me directly on Teams so I can understand your use-cases. If you aren't on a Microsoft service team, autorest.swift would not output something useful for you because it's very specifically tailored to producing an Azure-specific, HTTP-based SDKs.

**Comment by neojf** [comment]
Got it. Thanks for your help!
